ChromeGaming/Community-Page

index.html
styles.css

I have fix the image issue which is happening in small device , it was creating a overflow at x axis and breaks the flow of page.
I changed the code of CSS to meet the requirements 
I even fixed the upload button issue , it was changing place mean it wasnt responsive to diff window size  ,but now it is responsive
Fixes #3 
<hr>
<hr>
[Screencast from 11-05-24 02:11:14 PM IST.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/112775332/dede211e-2ab9-499c-bd72-7a6b09c95136)
--- 
<br>

fixed issue #3

---

script.js

Fixed the Discord btn issue , i use `remove()` instead of simple `display : 'none'`.
`remove()` is more better than `display : 'none'` in performance wise if u dont want to show the btn again 
Fixes #2 
<hr>
<hr>
[Screencast from 11-05-24 03:18:25 PM IST.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/112775332/6226973a-58b7-4e99-97d5-c1c63d5533e5)
--- 
<br>

fixed discord btn issue #2

---

index.html

Font awesome cdn link added, footer copyright, social media icons are visible.
Fixes # #4 
<hr>
- [✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅] I have added screenshot for review.
<hr>
--- 
<br>

fixed issue #4

---

styles.css

Added Hover effect on social media icons

---

index.html
script.js
styles.css

Firstly, thanks for assigning me this issue.
- Added Email Verification in Subscribe Input Field HTML5 Validation
- Addition: I have also made a nice green success box that appears when the subscription is added with a cross to close it.
Fixes #47 
<hr>
<hr>
- **Success Message**
- **Validation**
--- 
<br>

Bug Fix + Feature Add in Subscribe Field issue #47

---

index.html
package-lock.json
script.js
styles.css

#40 the feature will be added.
<hr>
<hr>
[Screencast from 2024-05-13 12-50-07.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/fd228e7d-66f6-41b4-ae9b-84c1ead58ef9)
--- 
<br>

[Feature] : Search result added

---

about.html
styles.css

Hello PA @Durgesh4993,
I have completed the about page of your website which matches your theme. Added animation also to make it look more attractive
Issue resolved - #50

Added about page

---

styles.css

I had added a customised scrollbar to the website.
Fixes #48 
<hr>
<hr>
Please review my pull request.
--- 
<br>

Added a customised scroll bar

---

index.html
script.js
styles.css

Fixes #11 
I  created an effect where, upon hovering the cursor over the 'Home' , the color changes and an underline appears.
Refer to the below images.
**BEFORE**
**AFTER**

Added hover effect to navbar

---

index.html
script.js
styles.css

Added dark/light toggleicon to webpage
Fixes #23 
<hr>
--- 
<br>

Added dark/light mode to webpage

---

.vscode/settings.json
index.html
script.js
styles.css

The faq section and its responsiveness are made and the hover effect for the social-media icons is also implemented.
I trying to solve assigned work as #30 
Thank you so much for contributing to our repository 💗

Faq section

---

about.html
index.html

there is no routing or linking to other tabs . The about page is created but cannot be used unless linking isnt given.
Fixes #78
- Since only about page and index page have been created. The routing is provided to them. Once other pages are done they can be easily linked by just changing the name of the page.html . 
- For now other pages both in navbar and footer have been redirected to index.html
https://github.com/GameSphere-MultiPlayer/Community-Page/assets/136987759/6211f827-1ca7-406d-b759-77cc30661ed3
<hr>
<hr>
--- 
<br>

routing added

---

styles.css

Hello PA @Durgesh4993 ,
I have fixed color of search on clicking and reduced the margin of navbar also
Issue resolved - #83
If you want any changes kindly tell me,
Best regards.

Fixed color of search on clicking and reduced the margin of navbar also

---

index.html
script.js
styles.css

Fixes # <your_issue_number>
<hr>
<hr>
--- 
<br>

Pending changes exported from your codespace

---

index.html
script.js
styles.css

this issue no id **#92** 
I have Fixed search results displaying none when the user enters the wrong text then shouldn't show the search results container. I also changed the background color of the input  it's very clear, I changed the input from text to search, I have increased the correct width in the input.
<hr>
<hr>
I have changed a few issues
--- 
<br>

[New Feature]: SearchBar Some changes for search Related 

---

index.html

The Fauget.gif is not looking appealing in the white mode. It doesn't give a sense of spacing between the Navigation Menu and the next attached image. 
Fixes #139 
<hr>
<hr>
After Adding a Space:
--- 
<br>

Space added in Fauget.gif.

---

.github/workflows/autocomment-pr-raise.yml

This PR adds an auto-commenting feature, which auto-comments when new PRs are raised.
Fixes #129 
<hr>
<hr>
--- 
<br>

Fixes #129

---

.github/workflows/autocomment-issue.yml

This PR adds an auto-commenting feature to the new issues that'll be raised.
Fixes #127 
<hr>
<hr>
--- 
<br>

Fixes #127

---

about.html
styles.css

FIxes #154 
I have successfully added timeline in about us page
https://github.com/GameSphere-MultiPlayer/Community-Page/assets/147748752/5ccc8247-6b61-4774-887b-3f49bb8a1f7d
Merge this PR to see changes

Successfully Created the Timeline in the about page

---

index.html
script.js

Adding leaderboard using api
Fixes #170 
<hr>
<hr>
--- 
<br>

Adding leaderboard using api as said in issue #170

---

styles.css

By follow given guidelines resolve issue ,create responsive navbar if u want any changes please tell my mistakes I will correct it again
Fixes #116
<hr>

[Bug]: Responsive Search bar

---

index.html

The issue related to navigation behavior of footer tabs under the _Info_ section of home page has been resolved. Now each tab is correctly navigating to its corresponding webpages
Issue Number: #175 
&#9745; I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project. 
&#9745; I have performed a self-review of my own code or work. 
&#9745;My changes generates no new warnings.
&#9745;I have added screenshot for review.
<hr>
--- 
<br>

Fixed the navigation behavior of footer tabs! #175 

---

about.html
contribute.html
index.html
play.html
playgames.html
product.html
products.html

>Add light dark mode feature .
>Fixed some of broken Links like home page was not linked
>Made the button visible in light mode in pages like product,playgame ,contribute
Fixes #176 
<hr>
<hr>
Before button were not visible in some page I fixed that also
After changes
--- 
<br>

Added  Light and dark mode feature in Product page and fixed some visibility issues and broken links

---

script.js

I have added support for the website theme to persist through reloads, i.e. if a theme is once sent to dark or light, it will remain such even if website is reloaded or reopened after some time.
Fixes #184 
<hr>
--- 
<br>

Website theme persists through reload

---

script.js

Reverts GameSphere-MultiPlayer/Community-Page#220

Revert "Website theme persists through reload"

---

about.html

I have changed the colour of the headings different from the background so that the text is visible.
Fixes # <your_issue_number>
Fixes #101 
<hr>
<hr>
--- 
<br>

Solved issue #101- Headings like Legal, Info, Explore, etc are not visible

---

about.html
contribute.html
index.html
play.html
playgames.html
products.html

Fixes #180 
Successfully removed the navbar that was twice on products page and also corrected the links to the products page
Before
after

changes the navbar and changed the links to products page everywhere

---

public/css/styles.css

Fixed top navbar to make it visible even with the scroll. Made it responsive too.
Fixes # 108
<hr>
<hr>
--- 
<br>

Fixed navbar

---

server/package-lock.json
server/package.json
server/views/index.ejs

Fixes #227 
<hr>
<hr>
--- 
<br>

hover effect added to footer and bug fixed

---

server/views/contribute.ejs
server/views/play.ejs

Added footer to contribute  and play pages
Fixes #216 
<hr>
<hr>
--- 
<br>

Added footer section in product , play games ,contribute

---

public/css/styles.css
server/views/about.ejs

Fixed the visibility of text in light mode in all pages
Fixes #230 
<hr>
<hr>
All pages text in every modes
--- 
<br>

enhanced the visibility of text in all modes

---

server/views/index.ejs

Fixes #225 
Since there were many overlappings in the navbar , I changed the whole navbar and now it is responsive and UI has been enhanced, removed overlappings.
<hr>
<hr>
https://github.com/ChromeGaming/Community-Page/assets/102676949/abb12725-8f86-4b81-b768-e6e145dbe89e
--- 
<br>

UI Enhanced - Navbar

---

Learn.md

This pull request creates a new `Learn.md` file, which provides comprehensive learning resources for the technologies used in the project. The `Learn.md` file is structured to include separate sections for HTML, CSS, JavaScript, Node.js, and Express.js, each with a table of resources for easy reference.
Summary of changes:
- Added `Learn.md` file.
- Included sections for HTML, CSS, JavaScript, Node.js, and Express.js.
- Provided detailed resources for each technology in table format for better readability and accessibility.
Fixes #287
<hr>
<hr>
N/A
--- 
<br>

[Docs]: Create Learn.md File

---

server/views/about.ejs
server/views/contribute.ejs
server/views/index.ejs
server/views/play.ejs
server/views/playgames.ejs
server/views/products.ejs

The page icons have been added and should be working fine. 
Fixes #246 
<hr>
<br>

Added the page logo to all pages #246

---

index.html
public/css/styles.css

issue number:#222
issue-Feature enhancement- Navbar styling should be changed.
Overall look of the website is very good but navbar content styling and font style is not as the theme of the website. Navbar is the very first thing a user will notice so it should be based on the theme of the website. So I use a good font and apply some CSS styling to change the font styling of the Navbar content.
I am also attaching images of the changes that I have created.
<hr>
- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or …

Navbar Content Style Update

---

server/views/about.ejs

- Fixed repeating elements in the navbar 
- Added padding for the about us text in the about section
Fixes #305 #304
<hr>
<hr>
Before:
After:
--- 
<br>

Completes 

---

public/css/styles.css
server/views/about.ejs
server/views/contribute.ejs
server/views/index.ejs
server/views/play.ejs
server/views/products.ejs

Hello PA @Durgesh4993 ,
Fixed Issue- #309

Fixed alignment and styled headings of all pages

---

.github/workflows/close-old-issue.yml

Implementing automatic closure for old issues to enhance repository cleanliness and focus on active discussions. This PR introduces customizable settings for defining inactivity thresholds, notification options, exemption mechanisms, closure conditions, integration with version control, and an audit trail.
Fixes #313
<hr>
<hr>
--- 
<br>

Implement Automatic Closure Feature for Old Issues

---

public/css/styles.css
server/views/about.ejs
server/views/index.ejs
server/views/play.ejs
server/views/playgames.ejs
server/views/products.ejs

Hello PA @Manaregr8 ,
Issue Resolved - #323 
- It matches the color theme of the website
- changed the font , due to this the logo's font is looking more appealing
- Added smooth transition

Added hover and transition on navlinks

---

public/css/styles.css
server/views/about.ejs
server/views/index.ejs
server/views/play.ejs
server/views/products.ejs

Issue resolved - #321 
https://github.com/ChromeGaming/Community-Page/assets/85826117/f5931d97-322e-4177-8e26-adbbc0576cfb

re-styled share button icons

---

server/views/about.ejs
server/views/index.ejs
server/views/products.ejs

fixed dark theme in all pages

---

server/views/index.ejs

fixed menu in index file

---

public/css/styles.css
server/views/index.ejs

hello PA @Manaregr8 
Issue resolved- #344

added github avatar of each contributer annd their profile link dynamically

---

public/css/styles.css
public/js/script.js
server/views/about.ejs
server/views/index.ejs
server/views/partials/rateus.ejs
server/views/play.ejs
server/views/playgames.ejs
server/views/products.ejs

I have added Rateus page in website which will help the users to quickly review the website and give feedback about the same.
Fixes #339 
<hr>
- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ X] I have …

Rate us page is added

---

README.md

no mention techstack in project so add  it and make boundaries in project 
Fixes #352 
<hr>
- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
<hr>
--- 
<br>

make  changes in readme #352

---

public/css/styles.css
server/views/about.ejs
server/views/index.ejs

Animation responsiveness

---

server/views/index.ejs

change the icon color in dark theme in homepage
Fixes #365 
--- 
<br>

changed_icons_color

---

public/css/styles.css

changed twitter icon
Fixes #363 
<hr>
- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [X ] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
--- 
<br>

added 'X' icon

---

public/js/script.js
server/views/about.ejs
server/views/index.ejs
server/views/partials/rateus.ejs
server/views/play.ejs
server/views/playgames.ejs
server/views/products.ejs

Added a progress bar which matches the UI of website, on every page in the website which will progress as the page scrolls up and down .
Fixes #383
<hr>
<hr>
https://github.com/user-attachments/assets/f3a708d0-3537-415e-baf4-5e2bff810f0f
--- 
<br>

Added a progress bar on every page .

---

server/views/index.ejs

I have added suitable color in different modes so that all the navbar links and also icons are clearly visible .
Fixes #384
<hr>
<hr>
https://github.com/user-attachments/assets/4586e2a6-b1a2-4cd1-9a0b-123edfb3de9f
--- 
<br>

Navbar links are now visible in every mode .

---

.idea/.gitignore
.idea/Community-Page.iml
.idea/material_theme_project_new.xml
.idea/modules.xml
.idea/vcs.xml
public/css/styles.css

just fixed the `overflow-x:hidden`
Fixes #381 
<hr>
<hr>
No scroll in the x-axis
--- 
<br>

fixed issue #381

---

public/css/styles.css
public/js/script.js
server/package-lock.json

Added images of contributors to the leaderboard
Fixes #395 
<hr>
- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for review.
<hr>
--- 
<br>

Add images of contributors in leaderboard

---

public/css/styles.css

Added hover effect on subscribe buttton and  social icons
#399 
<hr>
<hr>
--- 
<br>

Added hover effect

---

server/views/about.ejs
server/views/index.ejs
server/views/play.ejs
server/views/products.ejs

added search bar functionality

---

public/css/styles.css
server/views/index.ejs

fixe navlinks in smaller screens

---

public/js/script.js

Fixes #419 
Previously the dark-light modes wasnt consistent. If user changes theme mode in one page, and went to another, the theme mode changes were not consistent, i resolved the issue, and make theme mode consistent across all pages.
<hr>
<hr>
Video of proper working of feature: 
https://github.com/user-attachments/assets/b5cd60f2-0c21-404b-aef4-9ec37fb769c1
Thanks for assigning me this issue.
--- 
<br>

Resolved dark mode inconsistency issue

---

public/css/styles.css
server/views/products.ejs

fixed position of share button in all pages

---

public/css/styles.css
server/views/index.ejs

added testimonials section

---

server/views/about.ejs

Fixed contact us

---

server/index.js
server/views/about.ejs
server/views/index.ejs
server/views/play.ejs
server/views/privacy.ejs
server/views/products.ejs

Added privacy policy page
